
DROP VIEW birth_record;
DROP VIEW death_certificate;
DROP VIEW criminal_record;

DROP TABLE birth CASCADE;
DROP TABLE classmate CASCADE;
DROP TABLE criminal CASCADE;
DROP TABLE death CASCADE;
DROP TABLE hospital CASCADE;
DROP TABLE victim CASCADE;
DROP TABLE driver_license CASCADE;
DROP TABLE incident CASCADE;
DROP TABLE witness CASCADE;

DROP TYPE CRIMINAL_TYPE;
DROP TYPE PUNISHMENT_TYPE;
DROP TYPE DEATH_TYPE;
DROP TYPE DEATH_STATUS;
DROP TYPE VEHICLE_TYPE;
DROP TYPE INCIDENT_TYPE;
